// 📌 layout.tsx (Server Component)
import "./globals.css";
import ReduxProvider from "@/components/Provider"; // ✅ Import the Redux wrapper

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="main">
        <ReduxProvider>{children}</ReduxProvider> {/* ✅ Wrap the app in Redux */}
      </body>
    </html>
  );
}
